In [ ]:
import pandas as pd 
import sqlalchemy

In [ ]:
df1 = pd.read_csv('usa_sales.csv')
df2 = pd.read_csv('canada_sales.csv')

**USA**

In [ ]:
df1.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,236670,Wired Headphones,2,11.99,08/31/19 22:21,"359 Spruce St, Seattle, WA 98101"
1,236671,Bose SoundSport Headphones,1,99.99,08/15/19 15:11,"492 Ridge St, Dallas, TX 75001"
2,236672,iPhone,1,700.0,08/06/19 14:40,"149 7th St, Portland, OR 97035"
3,236673,AA Batteries (4-pack),2,3.84,08/29/19 20:59,"631 2nd St, Los Angeles, CA 90001"
4,236674,AA Batteries (4-pack),2,3.84,08/15/19 19:53,"736 14th St, New York City, NY 10001"

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12011 entries, 0 to 12010
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order ID          11983 non-null  object
 1   Product           11983 non-null  object
 2   Quantity Ordered  11983 non-null  object
 3   Price Each        11983 non-null  object
 4   Order Date        11983 non-null  object
 5   Purchase Address  11983 non-null  object
dtypes: object(6)
memory usage: 563.1+ KB

In [ ]:
df1.isnull().sum()

Order ID            28
Product             28
Quantity Ordered    28
Price Each          28
Order Date          28
Purchase Address    28
dtype: int64

In [ ]:
df1 = df1.dropna()

In [ ]:
df1.isnull().sum()

Order ID            0
Product             0
Quantity Ordered    0
Price Each          0
Order Date          0
Purchase Address    0
dtype: int64

In [ ]:
df1.duplicated().sum()

43

In [ ]:
df1 = df1.drop_duplicates()
df1.duplicated().sum()

0

In [ ]:
df1['Price Each'] = pd.to_numeric(df1['Price Each'], errors='coerce')  # ensures numeric values
df1['Price Each'] = df1['Price Each'].fillna(0).round().astype(int)   # handle NaN, then round

In [ ]:
df1.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,236670,Wired Headphones,2,12,08/31/19 22:21,"359 Spruce St, Seattle, WA 98101"
1,236671,Bose SoundSport Headphones,1,100,08/15/19 15:11,"492 Ridge St, Dallas, TX 75001"
2,236672,iPhone,1,700,08/06/19 14:40,"149 7th St, Portland, OR 97035"
3,236673,AA Batteries (4-pack),2,4,08/29/19 20:59,"631 2nd St, Los Angeles, CA 90001"
4,236674,AA Batteries (4-pack),2,4,08/15/19 19:53,"736 14th St, New York City, NY 10001"

**CANADA**

In [63]:
df2.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"128 Elm St, Quebec City"
1,NaN,NaN,NaN,NaN,NaN,"113 Oak St, Ottawa"
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"116 Elm St, Winnipeg"
3,176560,Google Phone,1,600,04/12/19 14:38,"149 Broadway, Edmonton"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"121 Maple St, Vancouver"

In [22]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18383 entries, 0 to 18382
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order ID          18324 non-null  object
 1   Product           18324 non-null  object
 2   Quantity Ordered  18324 non-null  object
 3   Price Each        18324 non-null  object
 4   Order Date        18324 non-null  object
 5   Purchase Address  18383 non-null  object
dtypes: object(6)
memory usage: 861.8+ KB

In [26]:
df2.isnull().sum()

Order ID            59
Product             59
Quantity Ordered    59
Price Each          59
Order Date          59
Purchase Address     0
dtype: int64

In [90]:
df2 = df2.dropna()

In [92]:
df2.isnull().sum()

Order ID            0
Product             0
Quantity Ordered    0
Price Each          0
Order Date          0
Purchase Address    0
dtype: int64

In [94]:
df2.duplicated().sum()

0

In [136]:
df2['Price Each'] = pd.to_numeric(df2['Price Each'], errors='coerce')  # ensures numeric values
df2['Price Each'] = df2['Price Each'].fillna(0).round().astype(int)   # handle NaN, then round

In [178]:
exchange_rate = 1.25
df2['price_usd'] = df2['Price Each'] * exchange_rate

In [180]:
df2.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,price_usd
0,176558,USB-C Charging Cable,2,12,04/19/19 08:46,"128 Elm St, Quebec City",15.0
2,176559,Bose SoundSport Headphones,1,100,04/07/19 22:30,"116 Elm St, Winnipeg",125.0
3,176560,Google Phone,1,600,04/12/19 14:38,"149 Broadway, Edmonton",750.0
4,176560,Wired Headphones,1,12,04/12/19 14:38,"121 Maple St, Vancouver",15.0
5,176561,Wired Headphones,1,12,04/30/19 09:27,"123 Cedar Ave, Vancouver",15.0

**Merged**

In [162]:
merged_df= pd.concat([df1, df2], ignore_index=True)
merged_df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,price_usd
0,236670,Wired Headphones,2,12,08/31/19 22:21,"359 Spruce St, Seattle, WA 98101",NaN
1,236671,Bose SoundSport Headphones,1,100,08/15/19 15:11,"492 Ridge St, Dallas, TX 75001",NaN
2,236672,iPhone,1,700,08/06/19 14:40,"149 7th St, Portland, OR 97035",NaN
3,236673,AA Batteries (4-pack),2,4,08/29/19 20:59,"631 2nd St, Los Angeles, CA 90001",NaN
4,236674,AA Batteries (4-pack),2,4,08/15/19 19:53,"736 14th St, New York City, NY 10001",NaN

In [110]:
df1.shape

(11940, 6)

In [112]:
df2.shape

(18324, 6)

In [114]:
merged_df.shape

(30264, 6)

In [186]:
exchange_rate= 1.25
merged_df['price_usd'] = merged_df['Price Each'] * exchange_rate

In [176]:
merged_df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,price_usd
0,236670,Wired Headphones,2,12,08/31/19 22:21,"359 Spruce St, Seattle, WA 98101",15.0
1,236671,Bose SoundSport Headphones,1,100,08/15/19 15:11,"492 Ridge St, Dallas, TX 75001",125.0
2,236672,iPhone,1,700,08/06/19 14:40,"149 7th St, Portland, OR 97035",875.0
3,236673,AA Batteries (4-pack),2,4,08/29/19 20:59,"631 2nd St, Los Angeles, CA 90001",5.0
4,236674,AA Batteries (4-pack),2,4,08/15/19 19:53,"736 14th St, New York City, NY 10001",5.0

In [182]:
merged_df['price_usd'] = pd.to_numeric(merged_df['price_usd'], errors='coerce')  # ensures numeric values
merged_df['price_usd'] = merged_df['price_usd'].fillna(0).round().astype(int)   # handle NaN, then round

In [184]:
merged_df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,price_usd
0,236670,Wired Headphones,2,12,08/31/19 22:21,"359 Spruce St, Seattle, WA 98101",15
1,236671,Bose SoundSport Headphones,1,100,08/15/19 15:11,"492 Ridge St, Dallas, TX 75001",125
2,236672,iPhone,1,700,08/06/19 14:40,"149 7th St, Portland, OR 97035",875
3,236673,AA Batteries (4-pack),2,4,08/29/19 20:59,"631 2nd St, Los Angeles, CA 90001",5
4,236674,AA Batteries (4-pack),2,4,08/15/19 19:53,"736 14th St, New York City, NY 10001",5

In [200]:
db_url = "postgresql://exam_db_4zf2_user:hCxnd8Mr3VLMqRGyemkbEyBdHkmfBEgH@dpg-cvsrju9r0fns73dp1heg-a.oregon-postgres.render.com/exam_db_4zf2"
connection = sqlalchemy.create_engine(db_url)

merged_df.to_sql("sales_data", con=connection, if_exists="replace", index=False)

query = "SELECT * FROM sales_data LIMIT 5;"
result_df = pd.read_sql(query, con=connection)
result_df

OperationalError: (psycopg2.OperationalError) connection to server at "dpg-cvsrju9r0fns73dp1heg-a.oregon-postgres.render.com" (35.227.164.209), port 5432 failed: Connection timed out (0x0000274C/10060)
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [196]:
pip install psycopg2

Collecting psycopg2
  Downloading psycopg2-2.9.10-cp312-cp312-win_amd64.whl.metadata (5.0 kB)
Downloading psycopg2-2.9.10-cp312-cp312-win_amd64.whl (1.2 MB)
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   -- ------------------------------------- 0.1/1.2 MB 465.5 kB/s eta 0:00:03
   --- ------------------------------------ 0.1/1.2 MB 653.6 kB/s eta 0:00:02
   -------- ------------------------------- 0.3/1.2 MB 1.3 MB/s eta 0:00:01
   ------------------- -------------------- 0.6/1.2 MB 2.3 MB/s eta 0:00:01
   --------------------------- ------------ 0.8/1.2 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------  1.2/1.2 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------- 1.2/1.2 MB 3.1 MB/s eta 0:00:00
Installing collected packages: psycopg2
Successfully installed psycopg2-2.9.10
Note: you may need to restart the kernel to use updated packages.